#!/bin/sh

set -e

BOARD="multi_v7" # includes vexpress-v2p-ca9 and imx53qsb
FLAGS="O=o_${BOARD} ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- KBUILD_USER=root KBUILD_HOST=usbarmory"

rm -rf "o_${BOARD}"
mkdir -p "o_${BOARD}" # in case i commented out the previous rm(1)

#make $FLAGS "${BOARD}_defconfig"
make $FLAGS -j4 Image
make $FLAGS -j4 uImage zImage LOADADDR=0x70008000
make $FLAGS -j4 dtbs
make $FLAGS -j4 modules

# Check out scripts/package/Makefile - neat!
# patched buildtar to copy {,u,z}Image and *.dtb on arm
make $FLAGS tarxz-pkg
#make $FLAGS deb-pkg
